use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'

target 'GitFeed' do
  pod 'RxSwift', '~> 5.0'
  pod 'RxCocoa', '~> 5.0'
  pod 'Kingfisher', '~> 5.0'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '5.0'
        end
    end
end
